### ISSUE TITLE
Better description what this is and how to use it

### ISSUE THREAD

**Issue by fwenzel** [phrawzty/AudioAddict.bundle#17]
1) Nooot entirely sure what it'll do for me when I plug it into my plex instance
2) how do I install it?

**Comment by phrawzty** [comment]
1) It'll give you a nice intereface to the [AudioAddict](http://www.audioaddict.com/) sites, such as [DI.fm](http://di.fm) and [RadioTunes](http://radiotunes.com) (formerly Sky.fm).
2) Yeah, since this isn't an official Plex plugin, installation is a little bit more manual than I'd like.  I'll update the doc accordingly.

**Comment by fwenzel** [comment]
Thanks!
