### ISSUE TITLE
RadioTunes not working

### ISSUE THREAD

**Issue by prologic** [phrawzty/AudioAddict.bundle#40]
Put my listen key in from radiotunes.com/settings -> Hardware -> Listen Key

Every channel I've tried times out and errors out to a "network error".

Need to figure out where the logs are (*I enabeld debug logs in the plugin*) but not sure where they get stored.

**Comment by phrawzty** [comment]
Sorry to hear that it's not working for you. Try enabling `Force Refresh` the **first time** you load a service (i.e. RadioTunes) and see if that helps. Be sure to **disable** it once you've loaded a service successfully since it's resource intensive and unnecessary to leave enabled. Hopefully that will help.

Otherwise, the [Plex help page for server logs](https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files) will help you find the logs.

Let me know how you get on.

**Comment by prologic** [comment]
That seems to have worked. Although when you hit one of the services for the first time it ends up timing out the channel (*I guess?*) with "Channel is not responding".

I assume it just took too long; so I went ahead and turned off "Force Refresh" and things started to work.

Can you explain what's going on? :)

**Comment by phrawzty** [comment]
See "Force Refresh" in the [README]https://github.com/phrawzty/AudioAddict.bundle/blob/master/README.md#preferences). 😄
